chaihens:
  voucher:
    admin:
      web:
        #HTTP 监听端口
        port: 8088
        #嵌入式Web服务器的线程池配置
        threadPool:
          maxThreads: 200
          minThreads: 8
          idleTimeout: 60000
      dataSource:
        #数据库配置项参照 com.zaxxer.hikari.HikariConfig
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.99.100:32772/chaihens?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
logging:
  config: ./config/logback.xml